# Generated by Django 6.0.4 on 2026-04-28 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0003_payout'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
